name: route_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bottom_drawer: ^0.0.5
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_tappable_polyline: ^6.0.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  http: ^1.2.0
  intl: ^0.19.0
  latlong2: ^0.9.0
  permission_handler: ^11.2.0
  qr_flutter: ^4.1.0
  text_scroll: ^0.2.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
